export enum ErrorCodes {
  MOVIE_NOT_FOUND = 'MOVIE_NOT_FOUND',
  INVALID_MOVIE_ID = 'INVALID_MOVIE_ID',
  OMDB_API_ERROR = 'OMDB_API_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

